// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXMOaH1-VoeHDcLJOUs8xI5uG5e3M53Q',
    appId: '1:392315038850:web:f08ef7b93de345e833989b',
    messagingSenderId: '392315038850',
    projectId: 'fir-21312032',
    authDomain: 'fir-21312032.firebaseapp.com',
    storageBucket: 'fir-21312032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTRtUYUJcJnKITb_J9EzD2Krrl8RQBCA',
    appId: '1:392315038850:android:a59a8032f1a1e07e33989b',
    messagingSenderId: '392315038850',
    projectId: 'fir-21312032',
    storageBucket: 'fir-21312032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClS9OXf2dgxQd3agaGlYHZKpEPR3pWwz4',
    appId: '1:392315038850:ios:fc550dcb56244cd433989b',
    messagingSenderId: '392315038850',
    projectId: 'fir-21312032',
    storageBucket: 'fir-21312032.appspot.com',
    iosClientId: '392315038850-4du8a2tus56eakubm95fj7btrli4brkg.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projekGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClS9OXf2dgxQd3agaGlYHZKpEPR3pWwz4',
    appId: '1:392315038850:ios:03b108d8b3dd7b2433989b',
    messagingSenderId: '392315038850',
    projectId: 'fir-21312032',
    storageBucket: 'fir-21312032.appspot.com',
    iosClientId: '392315038850-n2s48idr09u269d13a2pkji6n6tgn80r.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projekGet.RunnerTests',
  );
}
